name: shengyu_flutter_plugins
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  # 适配屏幕
  flutter_screenutil: ^5.9.3

  # 网络图片缓存
  cached_network_image: ^3.4.1

  # 国际化
  intl: ^0.20.2

  # double精度
  decimal: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:  
  assets:
    - assets/images/

